services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: echos
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d echos"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    platform: linux/amd64
    environment:
      - POSTGRES_DATABASE_URL=postgresql://user:password@postgres:5432/echos
      - AGENT_NAME=test
    env_file:
      - echos_lab/.env
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "python -c 'from echos_lab.db.db_setup import init_db; init_db()'"